services:
  api:
    image: ghcr.io/andrecostaaa/gaps-notifier-api:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
